remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  'pattern-matching-ts on GitHub':
    - 'https://github.com/nrdlab/pattern-matching-ts'
